version: 1

formatters:
  default:
    format: '[%(asctime)s][%(levelname)s][in %(module)s]: %(message)s'

handlers:
  wsgi:
    class: 'logging.StreamHandler'
    stream: 'ext://flask.logging.wsgi_errors_stream'
    formatter: 'default'
  # console:
  #   class : logging.StreamHandler
  #   formatter: default
  #   level   : INFO
  #   stream  : ext://sys.stdout
  file:
    class : logging.handlers.RotatingFileHandler
    formatter: default
    filename: ./logs/service.log
    maxBytes: 10485760
    backupCount: 2

root:
  level: INFO
  handlers:
   - wsgi
  #  - console
   - file
